### ISSUE TITLE
Втулка _ СУИР.03.17.pdf

### ISSUE THREAD

**Issue by IOreshin** [OTS0/Computer_engineering_graphics#1]
Привет!
На этом чертеже главный вид тот, который получен разрезом, т.е. он должен располагаться слева. 
И нет ни одного диаметрального размера

**Comment by OTS0** [comment]
Привет!
Спасибо за интерес к моим работам! Действительно не указала знак диаметра в размере – первые работы)
Насчет главного вида, инженер в праве выбирать сам главный вид, поэтому не соглашусь с данным замечанием.

**Comment by IOreshin** [comment]
Главный вид, конечно же, выбирает инженер сам, но он должен следовать принципу, что на главном виде отражается наибольшее количество конструктивных элементов.
Но ладно, прошу прощения за душноту)
А какие впечатления от Компаса и как к нему пришли? Из личного интереса собираю статистику просто.

**Comment by OTS0** [comment]
В репозитории представлены учебные работы, работа в Kompas 3D – одно из условий преподавателя в университете)
Kompas 3D нравится своим удобным интерфейсом, не нужно тратить время на понимание программы. Однако есть и минус: для полноценной работы необходимо дополнительно загружать программы, так как учебной версии недостаточно даже для выполнения университетских заданий.

Например, при установке Solid Works можно сразу рассчитать нагрузку на конструкцию и использовать удобные функции для быстрого создания чертежа. В то же время в Kompas 3D доступны только базовые инструменты.
